### ISSUE TITLE
Broken religion icons.

### ISSUE THREAD

**Issue by Lysimachus** [DarkReborn/lux-invicta-repository#15]
With the new portrait update all religion icons have been broken. Somebody needs to look into why this is happening and I suspect it has to do with BLG which has been previously linked to issues of this type.

**Comment by tannerflick4** [comment]
Religion icons being broken is something which only affects people with certain PCs or resolutions. Nothing in game is affected by the icons though, which is good! I know it might effect your immersion, but I recommend you play with them broken or try changing your resolution. Best of luck!
