### ISSUE TITLE
icon issue

### ISSUE THREAD

**Issue by thesuccman** [DarkReborn/lux-invicta-repository#3]
the icons sem to be half-way through one another, like the wrong holder in demense is half the castle icon with another half of the councilor icon, oddly enough. also the ruler modifiers are bugged as well, in the wrong place and half-way cut off. the name, also. example: administration_B0.

**Comment by richvh** [comment]
I haven't seen the alert icon issue for over a week. I haven't seen the ruler modifier issue at all, but haven't been looking for it... are you sure you have the current version?

**Comment by thesuccman** [comment]
I'm sure. I downloaded it straight from GitHub, as I noticed the forum one wasn't updated. Is LI incompatible with Reaper's Due?

**Comment by richvh** [comment]
_When_ did you download it from Github? The current version on Github works fine with Reaper's Due, and I haven't seen those issues. Note that the version on Github is the development version, and constantly changing.
If you have screenshots of the problems, please share them, here or on the forum.

**Comment by thesuccman** [comment]
I'll try to update it again and get back to you.

**Comment by thesuccman** [comment]
Right, I updated it and the icon problem stopped. Any way it can auto update when you make a commit? Like on my computer.

**Comment by Caeser188** [comment]
Who are y'all?

**Comment by richvh** [comment]
No way to auto-update that I know of.
