### ISSUE TITLE
The reply for every achievement is always "A date to go down in history."

### ISSUE THREAD

**Issue by Apani763** [DarkReborn/lux-invicta-repository#5]
![2016-12-03](https://cloud.githubusercontent.com/assets/17948963/20860817/c81ccfbe-b981-11e6-959d-0e531b6a0cd3.png)

**Comment by richvh** [comment]
Yes. So? Are you offering to go through all the achievements and add achievement relevant reply text to them?

**Comment by Apani763** [comment]
I didn't realize "date" was intended as "calendary date" here, so I thought it was meant to be a comment for "The marriage game" instead of a catch-all response. Sorry.
